### ISSUE TITLE
Оператор Audit

### ISSUE THREAD

**Issue by Varrah** [waliot/rxjs-ru#28]
Перевожу его, в какую папку положить?

**Comment by Varrah** [comment]
Добавил в pipeable, надеюсь в этот раз все правильно понял

**Comment by mephistorine** [comment]
@Varrah все правильно, так как это оператор можно использовать только внутри метода `pipe` он может находится только в директории pipeable

**Comment by mephistorine** [comment]
@Varrah вы не знакомы ведь с предметной областью реактивного программирования?

**Comment by Varrah** [comment]
Нет, не знаком, увы
