### ISSUE TITLE
Добавить перевод для оператора "debounce"

### ISSUE THREAD

**Issue by mephistorine** [waliot/rxjs-ru#3]
Нужно добавить перевод для оператора [debounce](https://rxjs.dev/api/operators/debounce). Это потоковый оператор, который используется только внутри метода [`pipe`](https://rxjs.dev/api/index/class/Observable#pipe).

Более подробно о том как нужно добавлять перевод оператора можно прочесть в [CONTRIBUTING](https://github.com/waliot/rxjs-ru/blob/master/CONTRIBUTING.md) файле

**Comment by deatheguard** [comment]
https://github.com/waliot/rxjs-ru/pull/22
Если есть замечания, пишите!
