### ISSUE TITLE
 Добавить перевод для оператора "delayWhen"

### ISSUE THREAD

**Issue by mephistorine** [waliot/rxjs-ru#5]
Нужно добавить перевод для оператора [delayWhen](https://rxjs.dev/api/operators/delayWhen). Это потоковый оператор, который используется только внутри метода [`pipe`](https://rxjs.dev/api/index/class/Observable#pipe).

Более подробно о том как нужно добавлять перевод оператора можно прочесть в [CONTRIBUTING](https://github.com/waliot/rxjs-ru/blob/master/CONTRIBUTING.md) файле

**Comment by deatheguard** [comment]
Здравствуйте! Перевод нужен на английский?

**Comment by mephistorine** [comment]
Привет, наоборот. С английского на русский!

**Comment by deatheguard** [comment]
А, там просто уже русский в указанных для перевода репозиториях. Или я что-то путаю и перевод ещё нужен?🤔

**Comment by mephistorine** [comment]
@deatheguard нет, возможно вы что-то путаете. Нужно взять исходную документацию на английском с официального сайта [rxjs.dev](rxjs.dev) найти там соответсвующий оператор и перевести на русский его документацию.

**Comment by deatheguard** [comment]
Ага, поняла, в таком случае постараюсь заняться вечером после работы/на выходных

**Comment by mephistorine** [comment]
@deatheguard в таком случае я переназначу на вас задачу

**Comment by deatheguard** [comment]
https://github.com/deatheguard/rxjs-ru/pull/1/commits
Если где-то что-то не так, буду рада исправить!

**Comment by deatheguard** [comment]
https://github.com/deatheguard/rxjs-ru/pull/2/commits
Если где-то что-то не так, буду рада исправить!

**Comment by deatheguard** [comment]
https://github.com/waliot/rxjs-ru/pull/21
Если где-то что-то не так, буду рада исправить!
